# Generated by Django 5.2.6 on 2025-11-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_transaction_id',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
